# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'integracionporTrapecios.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1500, 861)
        Form.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.labelIngreso = QtWidgets.QLabel(Form)
        self.labelIngreso.setGeometry(QtCore.QRect(20, 20, 111, 31))
        self.labelIngreso.setAcceptDrops(True)
        self.labelIngreso.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelIngreso.setAutoFillBackground(False)
        self.labelIngreso.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 11pt \"Arial\";\n"
"")
        self.labelIngreso.setAlignment(QtCore.Qt.AlignCenter)
        self.labelIngreso.setWordWrap(False)
        self.labelIngreso.setOpenExternalLinks(True)
        self.labelIngreso.setObjectName("labelIngreso")
        self.Funcion = QtWidgets.QLabel(Form)
        self.Funcion.setGeometry(QtCore.QRect(20, 70, 111, 31))
        self.Funcion.setAcceptDrops(True)
        self.Funcion.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Funcion.setAutoFillBackground(False)
        self.Funcion.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.Funcion.setAlignment(QtCore.Qt.AlignCenter)
        self.Funcion.setWordWrap(False)
        self.Funcion.setOpenExternalLinks(True)
        self.Funcion.setObjectName("Funcion")
        self.labelFuncion = QtWidgets.QLabel(Form)
        self.labelFuncion.setGeometry(QtCore.QRect(140, 70, 251, 31))
        self.labelFuncion.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.labelFuncion.setText("")
        self.labelFuncion.setObjectName("labelFuncion")
        self.labelIntervalo = QtWidgets.QLabel(Form)
        self.labelIntervalo.setGeometry(QtCore.QRect(20, 120, 111, 31))
        self.labelIntervalo.setAcceptDrops(True)
        self.labelIntervalo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelIntervalo.setAutoFillBackground(False)
        self.labelIntervalo.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 11pt \"Arial\";\n"
"")
        self.labelIntervalo.setAlignment(QtCore.Qt.AlignCenter)
        self.labelIntervalo.setWordWrap(False)
        self.labelIntervalo.setOpenExternalLinks(True)
        self.labelIntervalo.setObjectName("labelIntervalo")
        self.Extremoizq = QtWidgets.QLabel(Form)
        self.Extremoizq.setGeometry(QtCore.QRect(20, 170, 111, 31))
        self.Extremoizq.setAcceptDrops(True)
        self.Extremoizq.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Extremoizq.setAutoFillBackground(False)
        self.Extremoizq.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.Extremoizq.setAlignment(QtCore.Qt.AlignCenter)
        self.Extremoizq.setWordWrap(False)
        self.Extremoizq.setOpenExternalLinks(True)
        self.Extremoizq.setObjectName("Extremoizq")
        self.labelestremoizq = QtWidgets.QLabel(Form)
        self.labelestremoizq.setGeometry(QtCore.QRect(140, 170, 251, 31))
        self.labelestremoizq.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.labelestremoizq.setText("")
        self.labelestremoizq.setObjectName("labelestremoizq")
        self.Extremodere = QtWidgets.QLabel(Form)
        self.Extremodere.setGeometry(QtCore.QRect(20, 220, 111, 31))
        self.Extremodere.setAcceptDrops(True)
        self.Extremodere.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Extremodere.setAutoFillBackground(False)
        self.Extremodere.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.Extremodere.setAlignment(QtCore.Qt.AlignCenter)
        self.Extremodere.setWordWrap(False)
        self.Extremodere.setOpenExternalLinks(True)
        self.Extremodere.setObjectName("Extremodere")
        self.labelextremodere = QtWidgets.QLabel(Form)
        self.labelextremodere.setGeometry(QtCore.QRect(140, 220, 251, 31))
        self.labelextremodere.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.labelextremodere.setText("")
        self.labelextremodere.setObjectName("labelextremodere")
        self.particiones = QtWidgets.QLabel(Form)
        self.particiones.setGeometry(QtCore.QRect(20, 270, 141, 31))
        self.particiones.setAcceptDrops(True)
        self.particiones.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.particiones.setAutoFillBackground(False)
        self.particiones.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.particiones.setAlignment(QtCore.Qt.AlignCenter)
        self.particiones.setWordWrap(False)
        self.particiones.setOpenExternalLinks(True)
        self.particiones.setObjectName("particiones")
        self.labelParticiones = QtWidgets.QLabel(Form)
        self.labelParticiones.setGeometry(QtCore.QRect(170, 270, 251, 31))
        self.labelParticiones.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.labelParticiones.setText("")
        self.labelParticiones.setObjectName("labelParticiones")
        self.botonCalcular = QtWidgets.QPushButton(Form)
        self.botonCalcular.setGeometry(QtCore.QRect(30, 330, 91, 41))
        self.botonCalcular.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"font: 87 12pt \"Arial\";")
        self.botonCalcular.setObjectName("botonCalcular")
        self.botonsalir = QtWidgets.QPushButton(Form)
        self.botonsalir.setGeometry(QtCore.QRect(390, 330, 91, 41))
        self.botonsalir.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"font: 87 12pt \"Arial\";")
        self.botonsalir.setObjectName("botonsalir")
        self.botonborrar = QtWidgets.QPushButton(Form)
        self.botonborrar.setGeometry(QtCore.QRect(150, 330, 91, 41))
        self.botonborrar.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"font: 87 12pt \"Arial\";")
        self.botonborrar.setObjectName("botonborrar")
        self.botongrafica = QtWidgets.QPushButton(Form)
        self.botongrafica.setGeometry(QtCore.QRect(270, 330, 91, 41))
        self.botongrafica.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"font: 87 12pt \"Arial\";")
        self.botongrafica.setObjectName("botongrafica")
        self.labelsalida = QtWidgets.QLabel(Form)
        self.labelsalida.setGeometry(QtCore.QRect(20, 390, 111, 31))
        self.labelsalida.setAcceptDrops(True)
        self.labelsalida.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelsalida.setAutoFillBackground(False)
        self.labelsalida.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 11pt \"Arial\";\n"
"")
        self.labelsalida.setAlignment(QtCore.Qt.AlignCenter)
        self.labelsalida.setWordWrap(False)
        self.labelsalida.setOpenExternalLinks(True)
        self.labelsalida.setObjectName("labelsalida")
        self.labelintegral = QtWidgets.QLabel(Form)
        self.labelintegral.setGeometry(QtCore.QRect(20, 440, 131, 31))
        self.labelintegral.setAcceptDrops(True)
        self.labelintegral.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelintegral.setAutoFillBackground(False)
        self.labelintegral.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 11pt \"Arial\";\n"
"")
        self.labelintegral.setAlignment(QtCore.Qt.AlignCenter)
        self.labelintegral.setWordWrap(False)
        self.labelintegral.setOpenExternalLinks(True)
        self.labelintegral.setObjectName("labelintegral")
        self.valorintegral = QtWidgets.QLabel(Form)
        self.valorintegral.setGeometry(QtCore.QRect(20, 490, 111, 31))
        self.valorintegral.setAcceptDrops(True)
        self.valorintegral.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.valorintegral.setAutoFillBackground(False)
        self.valorintegral.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.valorintegral.setAlignment(QtCore.Qt.AlignCenter)
        self.valorintegral.setWordWrap(False)
        self.valorintegral.setOpenExternalLinks(True)
        self.valorintegral.setObjectName("valorintegral")
        self.labelvalorintegral = QtWidgets.QLabel(Form)
        self.labelvalorintegral.setGeometry(QtCore.QRect(140, 490, 251, 31))
        self.labelvalorintegral.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.labelvalorintegral.setText("")
        self.labelvalorintegral.setObjectName("labelvalorintegral")
        self.Error = QtWidgets.QLabel(Form)
        self.Error.setGeometry(QtCore.QRect(20, 540, 111, 31))
        self.Error.setAcceptDrops(True)
        self.Error.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Error.setAutoFillBackground(False)
        self.Error.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.Error.setAlignment(QtCore.Qt.AlignCenter)
        self.Error.setWordWrap(False)
        self.Error.setOpenExternalLinks(True)
        self.Error.setObjectName("Error")
        self.labelerror = QtWidgets.QLabel(Form)
        self.labelerror.setGeometry(QtCore.QRect(140, 540, 251, 31))
        self.labelerror.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.labelerror.setText("")
        self.labelerror.setObjectName("labelerror")
        self.labelintegral_2 = QtWidgets.QLabel(Form)
        self.labelintegral_2.setGeometry(QtCore.QRect(160, 440, 251, 31))
        self.labelintegral_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.labelintegral_2.setObjectName("labelintegral_2")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(500, 10, 565, 203))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.botonUno_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.botonUno_2.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 87 14pt \"Arial Black\";")
        self.botonUno_2.setObjectName("botonUno_2")
        self.gridLayout_4.addWidget(self.botonUno_2, 0, 0, 1, 1)
        self.botonDos_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.botonDos_2.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 87 14pt \"Arial Black\";")
        self.botonDos_2.setObjectName("botonDos_2")
        self.gridLayout_4.addWidget(self.botonDos_2, 0, 1, 1, 1)
        self.botonTres_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.botonTres_2.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 87 14pt \"Arial Black\";")
        self.botonTres_2.setObjectName("botonTres_2")
        self.gridLayout_4.addWidget(self.botonTres_2, 0, 2, 1, 1)
        self.botonCuatro_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.botonCuatro_2.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 87 14pt \"Arial Black\";")
        self.botonCuatro_2.setObjectName("botonCuatro_2")
        self.gridLayout_4.addWidget(self.botonCuatro_2, 1, 0, 1, 1)
        self.botonCinco_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.botonCinco_2.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 87 14pt \"Arial Black\";")
        self.botonCinco_2.setObjectName("botonCinco_2")
        self.gridLayout_4.addWidget(self.botonCinco_2, 1, 1, 1, 1)
        self.botonSeis_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.botonSeis_2.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 87 14pt \"Arial Black\";")
        self.botonSeis_2.setObjectName("botonSeis_2")
        self.gridLayout_4.addWidget(self.botonSeis_2, 1, 2, 1, 1)
        self.botonSiete_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.botonSiete_2.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 87 14pt \"Arial Black\";")
        self.botonSiete_2.setObjectName("botonSiete_2")
        self.gridLayout_4.addWidget(self.botonSiete_2, 2, 0, 1, 1)
        self.botonOcho_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.botonOcho_2.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 87 14pt \"Arial Black\";")
        self.botonOcho_2.setObjectName("botonOcho_2")
        self.gridLayout_4.addWidget(self.botonOcho_2, 2, 1, 1, 1)
        self.botonNueve_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.botonNueve_2.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 87 14pt \"Arial Black\";")
        self.botonNueve_2.setObjectName("botonNueve_2")
        self.gridLayout_4.addWidget(self.botonNueve_2, 2, 2, 1, 1)
        self.botonCabierto_4 = QtWidgets.QPushButton(self.layoutWidget)
        self.botonCabierto_4.setStyleSheet("font: 87 14pt \"Arial Black\";\n"
"background-color: rgb(0, 170, 127);")
        self.botonCabierto_4.setObjectName("botonCabierto_4")
        self.gridLayout_4.addWidget(self.botonCabierto_4, 3, 0, 1, 1)
        self.botonCero_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.botonCero_2.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 87 14pt \"Arial Black\";")
        self.botonCero_2.setObjectName("botonCero_2")
        self.gridLayout_4.addWidget(self.botonCero_2, 3, 1, 1, 1)
        self.botonCerrado_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.botonCerrado_2.setStyleSheet("background-color: rgb(0, 170, 127);\n"
"font: 87 14pt \"Arial Black\";")
        self.botonCerrado_2.setObjectName("botonCerrado_2")
        self.gridLayout_4.addWidget(self.botonCerrado_2, 3, 2, 1, 1)
        self.botonCabierto_5 = QtWidgets.QPushButton(self.layoutWidget)
        self.botonCabierto_5.setStyleSheet("font: 87 14pt \"Arial Black\";\n"
"background-color: rgb(0, 170, 127);")
        self.botonCabierto_5.setObjectName("botonCabierto_5")
        self.gridLayout_4.addWidget(self.botonCabierto_5, 4, 0, 1, 1)
        self.botonPunto_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.botonPunto_2.setStyleSheet("background-color: rgb(0, 170, 127);\n"
"font: 87 14pt \"Arial Black\";")
        self.botonPunto_2.setObjectName("botonPunto_2")
        self.gridLayout_4.addWidget(self.botonPunto_2, 4, 1, 1, 1)
        self.botonCabierto_6 = QtWidgets.QPushButton(self.layoutWidget)
        self.botonCabierto_6.setStyleSheet("font: 87 14pt \"Arial Black\";\n"
"background-color: rgb(0, 170, 127);")
        self.botonCabierto_6.setObjectName("botonCabierto_6")
        self.gridLayout_4.addWidget(self.botonCabierto_6, 4, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_4, 0, 0, 5, 1)
        self.botonMas_15 = QtWidgets.QPushButton(self.layoutWidget)
        self.botonMas_15.setStyleSheet("font: 87 14pt \"Arial Black\";\n"
"background-color: rgb(0, 170, 127);")
        self.botonMas_15.setObjectName("botonMas_15")
        self.gridLayout_3.addWidget(self.botonMas_15, 0, 1, 1, 1)
        self.botonMas_16 = QtWidgets.QPushButton(self.layoutWidget)
        self.botonMas_16.setStyleSheet("font: 75 14pt \"Arial\";\n"
"background-color: rgb(0, 170, 127);")
        self.botonMas_16.setObjectName("botonMas_16")
        self.gridLayout_3.addWidget(self.botonMas_16, 0, 2, 1, 1)
        self.botonMas_17 = QtWidgets.QPushButton(self.layoutWidget)
        self.botonMas_17.setStyleSheet("font: 12pt \"Arial\";\n"
"background-color: rgb(0, 170, 127);")
        self.botonMas_17.setObjectName("botonMas_17")
        self.gridLayout_3.addWidget(self.botonMas_17, 0, 3, 1, 1)
        self.botonMas_18 = QtWidgets.QPushButton(self.layoutWidget)
        self.botonMas_18.setStyleSheet("font: 12pt \"Arial\";\n"
"background-color: rgb(0, 170, 127);")
        self.botonMas_18.setObjectName("botonMas_18")
        self.gridLayout_3.addWidget(self.botonMas_18, 0, 4, 1, 1)
        self.botonMenos_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.botonMenos_2.setStyleSheet("font: 87 14pt \"Arial Black\";\n"
"background-color: rgb(0, 170, 127);")
        self.botonMenos_2.setObjectName("botonMenos_2")
        self.gridLayout_3.addWidget(self.botonMenos_2, 1, 1, 1, 1)
        self.botonMas_19 = QtWidgets.QPushButton(self.layoutWidget)
        self.botonMas_19.setStyleSheet("font: 87 14pt \"Arial Black\";\n"
"background-color: rgb(0, 170, 127);")
        self.botonMas_19.setObjectName("botonMas_19")
        self.gridLayout_3.addWidget(self.botonMas_19, 1, 2, 1, 1)
        self.botonMas_20 = QtWidgets.QPushButton(self.layoutWidget)
        self.botonMas_20.setStyleSheet("font: 12pt \"Arial\";\n"
"background-color: rgb(0, 170, 127);")
        self.botonMas_20.setObjectName("botonMas_20")
        self.gridLayout_3.addWidget(self.botonMas_20, 1, 3, 1, 1)
        self.botonMas_21 = QtWidgets.QPushButton(self.layoutWidget)
        self.botonMas_21.setStyleSheet("font: 12pt \"Arial\";\n"
"background-color: rgb(0, 170, 127);")
        self.botonMas_21.setObjectName("botonMas_21")
        self.gridLayout_3.addWidget(self.botonMas_21, 1, 4, 1, 1)
        self.BotonMulti_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.BotonMulti_2.setStyleSheet("background-color: rgb(0, 170, 127);\n"
"font: 87 14pt \"Arial Black\";")
        self.BotonMulti_2.setObjectName("BotonMulti_2")
        self.gridLayout_3.addWidget(self.BotonMulti_2, 2, 1, 1, 1)
        self.botonMas_22 = QtWidgets.QPushButton(self.layoutWidget)
        self.botonMas_22.setStyleSheet("font: 87 14pt \"Arial Black\";\n"
"background-color: rgb(0, 170, 127);")
        self.botonMas_22.setObjectName("botonMas_22")
        self.gridLayout_3.addWidget(self.botonMas_22, 2, 2, 1, 1)
        self.botonMas_23 = QtWidgets.QPushButton(self.layoutWidget)
        self.botonMas_23.setStyleSheet("font: 12pt \"Arial\";\n"
"background-color: rgb(0, 170, 127);")
        self.botonMas_23.setObjectName("botonMas_23")
        self.gridLayout_3.addWidget(self.botonMas_23, 2, 3, 1, 1)
        self.botonMas_24 = QtWidgets.QPushButton(self.layoutWidget)
        self.botonMas_24.setStyleSheet("font: 12pt \"Arial\";\n"
"background-color: rgb(0, 170, 127);")
        self.botonMas_24.setObjectName("botonMas_24")
        self.gridLayout_3.addWidget(self.botonMas_24, 2, 4, 1, 1)
        self.botonDivision_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.botonDivision_2.setStyleSheet("font: 87 14pt \"Arial Black\";\n"
"background-color: rgb(0, 170, 127);")
        self.botonDivision_2.setObjectName("botonDivision_2")
        self.gridLayout_3.addWidget(self.botonDivision_2, 3, 1, 1, 1)
        self.botonMas_25 = QtWidgets.QPushButton(self.layoutWidget)
        self.botonMas_25.setStyleSheet("font: 12pt \"Arial\";\n"
"background-color: rgb(0, 170, 127);")
        self.botonMas_25.setObjectName("botonMas_25")
        self.gridLayout_3.addWidget(self.botonMas_25, 3, 2, 1, 1)
        self.botonMas_26 = QtWidgets.QPushButton(self.layoutWidget)
        self.botonMas_26.setStyleSheet("font: 12pt \"Arial\";\n"
"background-color: rgb(0, 170, 127);")
        self.botonMas_26.setObjectName("botonMas_26")
        self.gridLayout_3.addWidget(self.botonMas_26, 3, 3, 1, 1)
        self.botonMas_27 = QtWidgets.QPushButton(self.layoutWidget)
        self.botonMas_27.setStyleSheet("font: 12pt \"Arial\";\n"
"background-color: rgb(0, 170, 127);")
        self.botonMas_27.setObjectName("botonMas_27")
        self.gridLayout_3.addWidget(self.botonMas_27, 3, 4, 1, 1)
        self.botonPorcentaje_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.botonPorcentaje_2.setStyleSheet("font: 87 14pt \"Arial Black\";\n"
"background-color: rgb(0, 170, 127);")
        self.botonPorcentaje_2.setObjectName("botonPorcentaje_2")
        self.gridLayout_3.addWidget(self.botonPorcentaje_2, 4, 1, 1, 1)
        self.botonintegral = QtWidgets.QPushButton(self.layoutWidget)
        self.botonintegral.setStyleSheet("font: 87 14pt \"Arial Black\";\n"
"background-color: rgb(0, 170, 127);")
        self.botonintegral.setObjectName("botonintegral")
        self.gridLayout_3.addWidget(self.botonintegral, 4, 2, 1, 1)
        self.botonAC_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.botonAC_2.setStyleSheet("font: 87 14pt \"Arial Black\";\n"
"background-color: rgb(0, 170, 127);")
        self.botonAC_2.setObjectName("botonAC_2")
        self.gridLayout_3.addWidget(self.botonAC_2, 4, 4, 1, 1)
        self.BotonBorrar_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.BotonBorrar_2.setStyleSheet("background-color: rgb(0, 170, 127);\n"
"font: 87 14pt \"Arial Black\";")
        self.BotonBorrar_2.setObjectName("BotonBorrar_2")
        self.gridLayout_3.addWidget(self.BotonBorrar_2, 4, 3, 1, 1)

        self.retranslateUi(Form)
        self.botonborrar.clicked.connect(self.botonborrar.deleteLater)
        self.botonsalir.clicked.connect(Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Integración Númerica por Trapecios"))
        self.labelIngreso.setText(_translate("Form", "Ingreso:"))
        self.Funcion.setText(_translate("Form", "Función F(x) ="))
        self.labelIntervalo.setText(_translate("Form", "Intervalo:"))
        self.Extremoizq.setText(_translate("Form", "Extremo Izq  a ="))
        self.Extremodere.setText(_translate("Form", "Extremo Der  b ="))
        self.particiones.setText(_translate("Form", "Numero de Particiones  n ="))
        self.botonCalcular.setText(_translate("Form", "Calcular"))
        self.botonsalir.setText(_translate("Form", "Salir"))
        self.botonborrar.setText(_translate("Form", "Borrar"))
        self.botongrafica.setText(_translate("Form", "Grafica"))
        self.labelsalida.setText(_translate("Form", "Salida:"))
        self.labelintegral.setText(_translate("Form", "Integral :  "))
        self.valorintegral.setText(_translate("Form", "Valor de la Integral ="))
        self.Error.setText(_translate("Form", "Error ="))
        self.labelintegral_2.setText(_translate("Form", "∫_a^b▒f(x)dx"))
        self.botonUno_2.setText(_translate("Form", "1"))
        self.botonUno_2.setShortcut(_translate("Form", "1"))
        self.botonDos_2.setText(_translate("Form", "2"))
        self.botonDos_2.setShortcut(_translate("Form", "2"))
        self.botonTres_2.setText(_translate("Form", "3"))
        self.botonTres_2.setShortcut(_translate("Form", "3"))
        self.botonCuatro_2.setText(_translate("Form", "4"))
        self.botonCuatro_2.setShortcut(_translate("Form", "4"))
        self.botonCinco_2.setText(_translate("Form", "5"))
        self.botonCinco_2.setShortcut(_translate("Form", "5"))
        self.botonSeis_2.setText(_translate("Form", "6"))
        self.botonSeis_2.setShortcut(_translate("Form", "6"))
        self.botonSiete_2.setText(_translate("Form", "7"))
        self.botonSiete_2.setShortcut(_translate("Form", "7"))
        self.botonOcho_2.setText(_translate("Form", "8"))
        self.botonOcho_2.setShortcut(_translate("Form", "8"))
        self.botonNueve_2.setText(_translate("Form", "9"))
        self.botonNueve_2.setShortcut(_translate("Form", "9"))
        self.botonCabierto_4.setText(_translate("Form", "("))
        self.botonCabierto_4.setShortcut(_translate("Form", "("))
        self.botonCero_2.setText(_translate("Form", "0"))
        self.botonCero_2.setShortcut(_translate("Form", "0"))
        self.botonCerrado_2.setText(_translate("Form", ")"))
        self.botonCerrado_2.setShortcut(_translate("Form", ")"))
        self.botonCabierto_5.setText(_translate("Form", "["))
        self.botonCabierto_5.setShortcut(_translate("Form", "("))
        self.botonPunto_2.setText(_translate("Form", "."))
        self.botonPunto_2.setShortcut(_translate("Form", "."))
        self.botonCabierto_6.setText(_translate("Form", "]"))
        self.botonCabierto_6.setShortcut(_translate("Form", "("))
        self.botonMas_15.setText(_translate("Form", "+"))
        self.botonMas_15.setShortcut(_translate("Form", "+"))
        self.botonMas_16.setText(_translate("Form", "√"))
        self.botonMas_16.setShortcut(_translate("Form", "+"))
        self.botonMas_17.setText(_translate("Form", "exp"))
        self.botonMas_17.setShortcut(_translate("Form", "+"))
        self.botonMas_18.setText(_translate("Form", "tan"))
        self.botonMas_18.setShortcut(_translate("Form", "+"))
        self.botonMenos_2.setText(_translate("Form", "-"))
        self.botonMenos_2.setShortcut(_translate("Form", "-"))
        self.botonMas_19.setText(_translate("Form", "^"))
        self.botonMas_19.setShortcut(_translate("Form", "+"))
        self.botonMas_20.setText(_translate("Form", "log"))
        self.botonMas_20.setShortcut(_translate("Form", "+"))
        self.botonMas_21.setText(_translate("Form", "sec"))
        self.botonMas_21.setShortcut(_translate("Form", "+"))
        self.BotonMulti_2.setText(_translate("Form", "x"))
        self.BotonMulti_2.setShortcut(_translate("Form", "*"))
        self.botonMas_22.setText(_translate("Form", "π"))
        self.botonMas_22.setShortcut(_translate("Form", "+"))
        self.botonMas_23.setText(_translate("Form", "sin"))
        self.botonMas_23.setShortcut(_translate("Form", "+"))
        self.botonMas_24.setText(_translate("Form", "csc"))
        self.botonMas_24.setShortcut(_translate("Form", "+"))
        self.botonDivision_2.setText(_translate("Form", "÷"))
        self.botonDivision_2.setShortcut(_translate("Form", "/"))
        self.botonMas_25.setText(_translate("Form", "ln"))
        self.botonMas_25.setShortcut(_translate("Form", "+"))
        self.botonMas_26.setText(_translate("Form", "cos"))
        self.botonMas_26.setShortcut(_translate("Form", "+"))
        self.botonMas_27.setText(_translate("Form", "cot"))
        self.botonMas_27.setShortcut(_translate("Form", "+"))
        self.botonPorcentaje_2.setText(_translate("Form", "%"))
        self.botonPorcentaje_2.setShortcut(_translate("Form", "%"))
        self.botonintegral.setText(_translate("Form", "∫"))
        self.botonintegral.setShortcut(_translate("Form", "+"))
        self.botonAC_2.setText(_translate("Form", "C"))
        self.BotonBorrar_2.setText(_translate("Form", "="))
        self.BotonBorrar_2.setShortcut(_translate("Form", "Esc"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

