# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Metodo_Montecarlo.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(593, 686)
        Form.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.labelfuncion = QtWidgets.QTextEdit(Form)
        self.labelfuncion.setGeometry(QtCore.QRect(10, 20, 111, 31))
        self.labelfuncion.setStyleSheet("font: 12pt \"Arial\";\n"
"background-color: rgb(170, 170, 255);")
        self.labelfuncion.setObjectName("labelfuncion")
        self.labelfuncionedit = QtWidgets.QPushButton(Form)
        self.labelfuncionedit.setGeometry(QtCore.QRect(130, 20, 251, 31))
        self.labelfuncionedit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.labelfuncionedit.setText("")
        self.labelfuncionedit.setObjectName("labelfuncionedit")
        self.labelIntervalo = QtWidgets.QLabel(Form)
        self.labelIntervalo.setGeometry(QtCore.QRect(10, 70, 111, 31))
        self.labelIntervalo.setAcceptDrops(True)
        self.labelIntervalo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelIntervalo.setAutoFillBackground(False)
        self.labelIntervalo.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 11pt \"Arial\";\n"
"")
        self.labelIntervalo.setAlignment(QtCore.Qt.AlignCenter)
        self.labelIntervalo.setWordWrap(False)
        self.labelIntervalo.setOpenExternalLinks(True)
        self.labelIntervalo.setObjectName("labelIntervalo")
        self.limiinfeA = QtWidgets.QLabel(Form)
        self.limiinfeA.setGeometry(QtCore.QRect(10, 120, 111, 31))
        self.limiinfeA.setAcceptDrops(True)
        self.limiinfeA.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.limiinfeA.setAutoFillBackground(False)
        self.limiinfeA.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.limiinfeA.setAlignment(QtCore.Qt.AlignCenter)
        self.limiinfeA.setWordWrap(False)
        self.limiinfeA.setOpenExternalLinks(True)
        self.limiinfeA.setObjectName("limiinfeA")
        self.labellimitinferiora = QtWidgets.QLabel(Form)
        self.labellimitinferiora.setGeometry(QtCore.QRect(130, 120, 251, 31))
        self.labellimitinferiora.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.labellimitinferiora.setText("")
        self.labellimitinferiora.setObjectName("labellimitinferiora")
        self.limSuperiorB = QtWidgets.QLabel(Form)
        self.limSuperiorB.setGeometry(QtCore.QRect(10, 170, 111, 31))
        self.limSuperiorB.setAcceptDrops(True)
        self.limSuperiorB.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.limSuperiorB.setAutoFillBackground(False)
        self.limSuperiorB.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.limSuperiorB.setAlignment(QtCore.Qt.AlignCenter)
        self.limSuperiorB.setWordWrap(False)
        self.limSuperiorB.setOpenExternalLinks(True)
        self.limSuperiorB.setObjectName("limSuperiorB")
        self.labelsuperior = QtWidgets.QLabel(Form)
        self.labelsuperior.setGeometry(QtCore.QRect(130, 170, 251, 31))
        self.labelsuperior.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.labelsuperior.setText("")
        self.labelsuperior.setObjectName("labelsuperior")
        self.numPuntos = QtWidgets.QLabel(Form)
        self.numPuntos.setGeometry(QtCore.QRect(10, 220, 141, 31))
        self.numPuntos.setAcceptDrops(True)
        self.numPuntos.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.numPuntos.setAutoFillBackground(False)
        self.numPuntos.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.numPuntos.setAlignment(QtCore.Qt.AlignCenter)
        self.numPuntos.setWordWrap(False)
        self.numPuntos.setOpenExternalLinks(True)
        self.numPuntos.setObjectName("numPuntos")
        self.labelnumpuntos = QtWidgets.QLabel(Form)
        self.labelnumpuntos.setGeometry(QtCore.QRect(160, 220, 251, 31))
        self.labelnumpuntos.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.labelnumpuntos.setText("")
        self.labelnumpuntos.setObjectName("labelnumpuntos")
        self.cotasuperior = QtWidgets.QLabel(Form)
        self.cotasuperior.setGeometry(QtCore.QRect(10, 270, 111, 31))
        self.cotasuperior.setAcceptDrops(True)
        self.cotasuperior.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cotasuperior.setAutoFillBackground(False)
        self.cotasuperior.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.cotasuperior.setAlignment(QtCore.Qt.AlignCenter)
        self.cotasuperior.setWordWrap(False)
        self.cotasuperior.setOpenExternalLinks(True)
        self.cotasuperior.setObjectName("cotasuperior")
        self.labelcotasuperior = QtWidgets.QLabel(Form)
        self.labelcotasuperior.setGeometry(QtCore.QRect(130, 270, 251, 31))
        self.labelcotasuperior.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.labelcotasuperior.setText("")
        self.labelcotasuperior.setObjectName("labelcotasuperior")
        self.botonCalcular = QtWidgets.QPushButton(Form)
        self.botonCalcular.setGeometry(QtCore.QRect(10, 330, 91, 41))
        self.botonCalcular.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"font: 87 12pt \"Arial\";")
        self.botonCalcular.setObjectName("botonCalcular")
        self.valorintegral = QtWidgets.QLabel(Form)
        self.valorintegral.setGeometry(QtCore.QRect(10, 390, 111, 31))
        self.valorintegral.setAcceptDrops(True)
        self.valorintegral.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.valorintegral.setAutoFillBackground(False)
        self.valorintegral.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.valorintegral.setAlignment(QtCore.Qt.AlignCenter)
        self.valorintegral.setWordWrap(False)
        self.valorintegral.setOpenExternalLinks(True)
        self.valorintegral.setObjectName("valorintegral")
        self.labelvalorintegral = QtWidgets.QLabel(Form)
        self.labelvalorintegral.setGeometry(QtCore.QRect(130, 390, 251, 31))
        self.labelvalorintegral.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.labelvalorintegral.setText("")
        self.labelvalorintegral.setObjectName("labelvalorintegral")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 440, 571, 203))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.botonUno = QtWidgets.QPushButton(self.layoutWidget)
        self.botonUno.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 87 14pt \"Arial Black\";")
        self.botonUno.setObjectName("botonUno")
        self.gridLayout.addWidget(self.botonUno, 0, 0, 1, 1)
        self.botonDos = QtWidgets.QPushButton(self.layoutWidget)
        self.botonDos.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 87 14pt \"Arial Black\";")
        self.botonDos.setObjectName("botonDos")
        self.gridLayout.addWidget(self.botonDos, 0, 1, 1, 1)
        self.botonTres = QtWidgets.QPushButton(self.layoutWidget)
        self.botonTres.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 87 14pt \"Arial Black\";")
        self.botonTres.setObjectName("botonTres")
        self.gridLayout.addWidget(self.botonTres, 0, 2, 1, 1)
        self.botonCuatro = QtWidgets.QPushButton(self.layoutWidget)
        self.botonCuatro.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 87 14pt \"Arial Black\";")
        self.botonCuatro.setObjectName("botonCuatro")
        self.gridLayout.addWidget(self.botonCuatro, 1, 0, 1, 1)
        self.botonCinco = QtWidgets.QPushButton(self.layoutWidget)
        self.botonCinco.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 87 14pt \"Arial Black\";")
        self.botonCinco.setObjectName("botonCinco")
        self.gridLayout.addWidget(self.botonCinco, 1, 1, 1, 1)
        self.botonSeis = QtWidgets.QPushButton(self.layoutWidget)
        self.botonSeis.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 87 14pt \"Arial Black\";")
        self.botonSeis.setObjectName("botonSeis")
        self.gridLayout.addWidget(self.botonSeis, 1, 2, 1, 1)
        self.botonSiete = QtWidgets.QPushButton(self.layoutWidget)
        self.botonSiete.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 87 14pt \"Arial Black\";")
        self.botonSiete.setObjectName("botonSiete")
        self.gridLayout.addWidget(self.botonSiete, 2, 0, 1, 1)
        self.botonOcho = QtWidgets.QPushButton(self.layoutWidget)
        self.botonOcho.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 87 14pt \"Arial Black\";")
        self.botonOcho.setObjectName("botonOcho")
        self.gridLayout.addWidget(self.botonOcho, 2, 1, 1, 1)
        self.botonNueve = QtWidgets.QPushButton(self.layoutWidget)
        self.botonNueve.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 87 14pt \"Arial Black\";")
        self.botonNueve.setObjectName("botonNueve")
        self.gridLayout.addWidget(self.botonNueve, 2, 2, 1, 1)
        self.botonCabierto = QtWidgets.QPushButton(self.layoutWidget)
        self.botonCabierto.setStyleSheet("font: 87 14pt \"Arial Black\";\n"
"background-color: rgb(0, 170, 127);")
        self.botonCabierto.setObjectName("botonCabierto")
        self.gridLayout.addWidget(self.botonCabierto, 3, 0, 1, 1)
        self.botonCero = QtWidgets.QPushButton(self.layoutWidget)
        self.botonCero.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 87 14pt \"Arial Black\";")
        self.botonCero.setObjectName("botonCero")
        self.gridLayout.addWidget(self.botonCero, 3, 1, 1, 1)
        self.botonCerrado = QtWidgets.QPushButton(self.layoutWidget)
        self.botonCerrado.setStyleSheet("background-color: rgb(0, 170, 127);\n"
"font: 87 14pt \"Arial Black\";")
        self.botonCerrado.setObjectName("botonCerrado")
        self.gridLayout.addWidget(self.botonCerrado, 3, 2, 1, 1)
        self.botonCabierto_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.botonCabierto_2.setStyleSheet("font: 87 14pt \"Arial Black\";\n"
"background-color: rgb(0, 170, 127);")
        self.botonCabierto_2.setObjectName("botonCabierto_2")
        self.gridLayout.addWidget(self.botonCabierto_2, 4, 0, 1, 1)
        self.botonPunto = QtWidgets.QPushButton(self.layoutWidget)
        self.botonPunto.setStyleSheet("background-color: rgb(0, 170, 127);\n"
"font: 87 14pt \"Arial Black\";")
        self.botonPunto.setObjectName("botonPunto")
        self.gridLayout.addWidget(self.botonPunto, 4, 1, 1, 1)
        self.botonCabierto_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.botonCabierto_3.setStyleSheet("font: 87 14pt \"Arial Black\";\n"
"background-color: rgb(0, 170, 127);")
        self.botonCabierto_3.setObjectName("botonCabierto_3")
        self.gridLayout.addWidget(self.botonCabierto_3, 4, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 5, 1)
        self.botonMas = QtWidgets.QPushButton(self.layoutWidget)
        self.botonMas.setStyleSheet("font: 87 14pt \"Arial Black\";\n"
"background-color: rgb(0, 170, 127);")
        self.botonMas.setObjectName("botonMas")
        self.gridLayout_2.addWidget(self.botonMas, 0, 1, 1, 1)
        self.botonMas_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.botonMas_2.setStyleSheet("font: 75 14pt \"Arial\";\n"
"background-color: rgb(0, 170, 127);")
        self.botonMas_2.setObjectName("botonMas_2")
        self.gridLayout_2.addWidget(self.botonMas_2, 0, 2, 1, 1)
        self.botonMas_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.botonMas_3.setStyleSheet("font: 12pt \"Arial\";\n"
"background-color: rgb(0, 170, 127);")
        self.botonMas_3.setObjectName("botonMas_3")
        self.gridLayout_2.addWidget(self.botonMas_3, 0, 3, 1, 1)
        self.botonMas_11 = QtWidgets.QPushButton(self.layoutWidget)
        self.botonMas_11.setStyleSheet("font: 12pt \"Arial\";\n"
"background-color: rgb(0, 170, 127);")
        self.botonMas_11.setObjectName("botonMas_11")
        self.gridLayout_2.addWidget(self.botonMas_11, 0, 4, 1, 1)
        self.botonMenos = QtWidgets.QPushButton(self.layoutWidget)
        self.botonMenos.setStyleSheet("font: 87 14pt \"Arial Black\";\n"
"background-color: rgb(0, 170, 127);")
        self.botonMenos.setObjectName("botonMenos")
        self.gridLayout_2.addWidget(self.botonMenos, 1, 1, 1, 1)
        self.botonMas_4 = QtWidgets.QPushButton(self.layoutWidget)
        self.botonMas_4.setStyleSheet("font: 87 14pt \"Arial Black\";\n"
"background-color: rgb(0, 170, 127);")
        self.botonMas_4.setObjectName("botonMas_4")
        self.gridLayout_2.addWidget(self.botonMas_4, 1, 2, 1, 1)
        self.botonMas_8 = QtWidgets.QPushButton(self.layoutWidget)
        self.botonMas_8.setStyleSheet("font: 12pt \"Arial\";\n"
"background-color: rgb(0, 170, 127);")
        self.botonMas_8.setObjectName("botonMas_8")
        self.gridLayout_2.addWidget(self.botonMas_8, 1, 3, 1, 1)
        self.botonMas_12 = QtWidgets.QPushButton(self.layoutWidget)
        self.botonMas_12.setStyleSheet("font: 12pt \"Arial\";\n"
"background-color: rgb(0, 170, 127);")
        self.botonMas_12.setObjectName("botonMas_12")
        self.gridLayout_2.addWidget(self.botonMas_12, 1, 4, 1, 1)
        self.BotonMulti = QtWidgets.QPushButton(self.layoutWidget)
        self.BotonMulti.setStyleSheet("background-color: rgb(0, 170, 127);\n"
"font: 87 14pt \"Arial Black\";")
        self.BotonMulti.setObjectName("BotonMulti")
        self.gridLayout_2.addWidget(self.BotonMulti, 2, 1, 1, 1)
        self.botonMas_7 = QtWidgets.QPushButton(self.layoutWidget)
        self.botonMas_7.setStyleSheet("font: 87 14pt \"Arial Black\";\n"
"background-color: rgb(0, 170, 127);")
        self.botonMas_7.setObjectName("botonMas_7")
        self.gridLayout_2.addWidget(self.botonMas_7, 2, 2, 1, 1)
        self.botonMas_9 = QtWidgets.QPushButton(self.layoutWidget)
        self.botonMas_9.setStyleSheet("font: 12pt \"Arial\";\n"
"background-color: rgb(0, 170, 127);")
        self.botonMas_9.setObjectName("botonMas_9")
        self.gridLayout_2.addWidget(self.botonMas_9, 2, 3, 1, 1)
        self.botonMas_13 = QtWidgets.QPushButton(self.layoutWidget)
        self.botonMas_13.setStyleSheet("font: 12pt \"Arial\";\n"
"background-color: rgb(0, 170, 127);")
        self.botonMas_13.setObjectName("botonMas_13")
        self.gridLayout_2.addWidget(self.botonMas_13, 2, 4, 1, 1)
        self.botonDivision = QtWidgets.QPushButton(self.layoutWidget)
        self.botonDivision.setStyleSheet("font: 87 14pt \"Arial Black\";\n"
"background-color: rgb(0, 170, 127);")
        self.botonDivision.setObjectName("botonDivision")
        self.gridLayout_2.addWidget(self.botonDivision, 3, 1, 1, 1)
        self.botonMas_5 = QtWidgets.QPushButton(self.layoutWidget)
        self.botonMas_5.setStyleSheet("font: 12pt \"Arial\";\n"
"background-color: rgb(0, 170, 127);")
        self.botonMas_5.setObjectName("botonMas_5")
        self.gridLayout_2.addWidget(self.botonMas_5, 3, 2, 1, 1)
        self.botonMas_10 = QtWidgets.QPushButton(self.layoutWidget)
        self.botonMas_10.setStyleSheet("font: 12pt \"Arial\";\n"
"background-color: rgb(0, 170, 127);")
        self.botonMas_10.setObjectName("botonMas_10")
        self.gridLayout_2.addWidget(self.botonMas_10, 3, 3, 1, 1)
        self.botonMas_14 = QtWidgets.QPushButton(self.layoutWidget)
        self.botonMas_14.setStyleSheet("font: 12pt \"Arial\";\n"
"background-color: rgb(0, 170, 127);")
        self.botonMas_14.setObjectName("botonMas_14")
        self.gridLayout_2.addWidget(self.botonMas_14, 3, 4, 1, 1)
        self.botonPorcentaje = QtWidgets.QPushButton(self.layoutWidget)
        self.botonPorcentaje.setStyleSheet("font: 87 14pt \"Arial Black\";\n"
"background-color: rgb(0, 170, 127);")
        self.botonPorcentaje.setObjectName("botonPorcentaje")
        self.gridLayout_2.addWidget(self.botonPorcentaje, 4, 1, 1, 1)
        self.botonMas_6 = QtWidgets.QPushButton(self.layoutWidget)
        self.botonMas_6.setStyleSheet("font: 87 14pt \"Arial Black\";\n"
"background-color: rgb(0, 170, 127);")
        self.botonMas_6.setObjectName("botonMas_6")
        self.gridLayout_2.addWidget(self.botonMas_6, 4, 2, 1, 1)
        self.BotonBorrar = QtWidgets.QPushButton(self.layoutWidget)
        self.BotonBorrar.setStyleSheet("background-color: rgb(0, 170, 127);\n"
"font: 87 14pt \"Arial Black\";")
        self.BotonBorrar.setObjectName("BotonBorrar")
        self.gridLayout_2.addWidget(self.BotonBorrar, 4, 3, 1, 1)
        self.botonAC = QtWidgets.QPushButton(self.layoutWidget)
        self.botonAC.setStyleSheet("font: 87 14pt \"Arial Black\";\n"
"background-color: rgb(0, 170, 127);")
        self.botonAC.setObjectName("botonAC")
        self.gridLayout_2.addWidget(self.botonAC, 4, 4, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Metodo de Montecarlo"))
        self.labelfuncion.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; color:#000000;\">Función </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:600; color:#000000;\">F(x):</span></p></body></html>"))
        self.labelIntervalo.setText(_translate("Form", "Intervalo:"))
        self.limiinfeA.setText(_translate("Form", "Limite inferior  a ="))
        self.limSuperiorB.setText(_translate("Form", "Limite superior  b ="))
        self.numPuntos.setText(_translate("Form", "Numero de Puntos N ="))
        self.cotasuperior.setText(_translate("Form", "Cota superior M ="))
        self.botonCalcular.setText(_translate("Form", "Calcular"))
        self.valorintegral.setText(_translate("Form", "Valor de la Integral ="))
        self.botonUno.setText(_translate("Form", "1"))
        self.botonUno.setShortcut(_translate("Form", "1"))
        self.botonDos.setText(_translate("Form", "2"))
        self.botonDos.setShortcut(_translate("Form", "2"))
        self.botonTres.setText(_translate("Form", "3"))
        self.botonTres.setShortcut(_translate("Form", "3"))
        self.botonCuatro.setText(_translate("Form", "4"))
        self.botonCuatro.setShortcut(_translate("Form", "4"))
        self.botonCinco.setText(_translate("Form", "5"))
        self.botonCinco.setShortcut(_translate("Form", "5"))
        self.botonSeis.setText(_translate("Form", "6"))
        self.botonSeis.setShortcut(_translate("Form", "6"))
        self.botonSiete.setText(_translate("Form", "7"))
        self.botonSiete.setShortcut(_translate("Form", "7"))
        self.botonOcho.setText(_translate("Form", "8"))
        self.botonOcho.setShortcut(_translate("Form", "8"))
        self.botonNueve.setText(_translate("Form", "9"))
        self.botonNueve.setShortcut(_translate("Form", "9"))
        self.botonCabierto.setText(_translate("Form", "("))
        self.botonCabierto.setShortcut(_translate("Form", "("))
        self.botonCero.setText(_translate("Form", "0"))
        self.botonCero.setShortcut(_translate("Form", "0"))
        self.botonCerrado.setText(_translate("Form", ")"))
        self.botonCerrado.setShortcut(_translate("Form", ")"))
        self.botonCabierto_2.setText(_translate("Form", "["))
        self.botonCabierto_2.setShortcut(_translate("Form", "("))
        self.botonPunto.setText(_translate("Form", "."))
        self.botonPunto.setShortcut(_translate("Form", "."))
        self.botonCabierto_3.setText(_translate("Form", "]"))
        self.botonCabierto_3.setShortcut(_translate("Form", "("))
        self.botonMas.setText(_translate("Form", "+"))
        self.botonMas.setShortcut(_translate("Form", "+"))
        self.botonMas_2.setText(_translate("Form", "√"))
        self.botonMas_2.setShortcut(_translate("Form", "+"))
        self.botonMas_3.setText(_translate("Form", "exp"))
        self.botonMas_3.setShortcut(_translate("Form", "+"))
        self.botonMas_11.setText(_translate("Form", "tan"))
        self.botonMas_11.setShortcut(_translate("Form", "+"))
        self.botonMenos.setText(_translate("Form", "-"))
        self.botonMenos.setShortcut(_translate("Form", "-"))
        self.botonMas_4.setText(_translate("Form", "^"))
        self.botonMas_4.setShortcut(_translate("Form", "+"))
        self.botonMas_8.setText(_translate("Form", "log"))
        self.botonMas_8.setShortcut(_translate("Form", "+"))
        self.botonMas_12.setText(_translate("Form", "sec"))
        self.botonMas_12.setShortcut(_translate("Form", "+"))
        self.BotonMulti.setText(_translate("Form", "x"))
        self.BotonMulti.setShortcut(_translate("Form", "*"))
        self.botonMas_7.setText(_translate("Form", "π"))
        self.botonMas_7.setShortcut(_translate("Form", "+"))
        self.botonMas_9.setText(_translate("Form", "sin"))
        self.botonMas_9.setShortcut(_translate("Form", "+"))
        self.botonMas_13.setText(_translate("Form", "csc"))
        self.botonMas_13.setShortcut(_translate("Form", "+"))
        self.botonDivision.setText(_translate("Form", "÷"))
        self.botonDivision.setShortcut(_translate("Form", "/"))
        self.botonMas_5.setText(_translate("Form", "ln"))
        self.botonMas_5.setShortcut(_translate("Form", "+"))
        self.botonMas_10.setText(_translate("Form", "cos"))
        self.botonMas_10.setShortcut(_translate("Form", "+"))
        self.botonMas_14.setText(_translate("Form", "cot"))
        self.botonMas_14.setShortcut(_translate("Form", "+"))
        self.botonPorcentaje.setText(_translate("Form", "%"))
        self.botonPorcentaje.setShortcut(_translate("Form", "%"))
        self.botonMas_6.setText(_translate("Form", "="))
        self.botonMas_6.setShortcut(_translate("Form", "+"))
        self.BotonBorrar.setText(_translate("Form", "C"))
        self.BotonBorrar.setShortcut(_translate("Form", "Esc"))
        self.botonAC.setText(_translate("Form", "AC"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

